import type { InvitationTemplate } from "./template-catalog";
export const generalTemplates: InvitationTemplate[] = [
  {
    id: "general-classic",
    name: "Día especial",
    kind: "general",
    mode: "sections",
    accent: "#7451ac",
    background: "#fff9ed",
    font: "serif",
    style: "classic",
    tagline: "Una celebración cálida",
  },
  {
    id: "general-modern",
    name: "Encuentro",
    kind: "general",
    mode: "sections",
    accent: "#247785",
    background: "#eff9fa",
    font: "sans",
    style: "modern",
    tagline: "Fresco y directo",
  },
  {
    id: "general-flyer-party",
    name: "Fiesta en color",
    kind: "general",
    mode: "flyer",
    accent: "#7451ac",
    background: "#fff1f6",
    font: "sans",
    style: "modern",
    tagline: "Texto grande, estrellas y celebración",
  },
  {
    id: "general-flyer-meet",
    name: "Nos encontramos",
    kind: "general",
    mode: "flyer",
    accent: "#247785",
    background: "#eff9fa",
    font: "serif",
    style: "classic",
    tagline: "Un lienzo sencillo para tu evento",
  },
  {
    id: "general-sections-bold",
    kind: "general",
    mode: "sections",
    name: "Energía viva",
    accent: "#bd375c",
    background: "#fff1e8",
    font: "sans",
    style: "modern",
    tagline: "Fiestas y cumpleaños con carácter",
  },
  {
    id: "general-flyer-conference",
    kind: "general",
    mode: "flyer",
    name: "Punto de encuentro",
    accent: "#165fbc",
    background: "#eef4ff",
    font: "sans",
    style: "modern",
    tagline: "Conferencias, lanzamientos y encuentros",
  },
];
