import type { InvitationTemplate } from "./template-catalog";
export const weddingTemplates: InvitationTemplate[] = [
  {
    id: "wedding-classic",
    name: "Amor clásico",
    kind: "wedding",
    mode: "sections",
    accent: "#9c6449",
    background: "#fff9ed",
    font: "serif",
    style: "classic",
    tagline: "Flores, historia y detalles",
  },
  {
    id: "wedding-modern",
    name: "Sí, minimal",
    kind: "wedding",
    mode: "sections",
    accent: "#6c795f",
    background: "#f1f4ec",
    font: "sans",
    style: "modern",
    tagline: "Líneas limpias y verde salvia",
  },
  {
    id: "wedding-flyer-floral",
    name: "Jardín de amor",
    kind: "wedding",
    mode: "flyer",
    accent: "#9c6449",
    background: "#fff9ed",
    font: "serif",
    style: "classic",
    tagline: "Láminas con flores y tipografía elegante",
  },
  {
    id: "wedding-flyer-editorial",
    name: "Nuestra portada",
    kind: "wedding",
    mode: "flyer",
    accent: "#44573e",
    background: "#f1f4ec",
    font: "sans",
    style: "modern",
    tagline: "Una historia con aire editorial",
  },
  {
    id: "wedding-sections-romance",
    kind: "wedding",
    mode: "sections",
    name: "Romance en rosa",
    accent: "#995d72",
    background: "#fff3f6",
    font: "serif",
    style: "classic",
    tagline: "Una historia romántica, a vuestro ritmo",
  },
  {
    id: "wedding-flyer-night",
    kind: "wedding",
    mode: "flyer",
    name: "Noche de gala",
    accent: "#d7bc83",
    background: "#222a32",
    font: "serif",
    style: "modern",
    tagline: "Elegancia nocturna y detalles en oro",
  },
];
